# Importing Libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly as px

# load Dataset from data directory

In [4]:
df = pd.read_csv('data/train.csv')

In [5]:
df

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,label
0,46264,1.457374,tcp,http,FIN,10,16,814,9878,17.154142,...,1,1,1,0,0,1,2,1,0,1
1,3575,0.654355,tcp,-,FIN,10,8,564,354,25.979782,...,1,1,1,0,0,0,1,1,0,1
2,43204,0.000002,udp,-,INT,2,0,1064,0,500000.001300,...,9,1,34,0,0,0,10,33,0,0
3,59869,0.000011,nvp,-,INT,2,0,180,0,90909.090200,...,14,14,14,0,0,0,15,14,0,1
4,1203,0.000004,udp,-,INT,2,0,168,0,250000.000600,...,1,1,1,0,0,0,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65860,718,0.000005,ipv6-opts,-,INT,2,0,200,0,200000.005100,...,2,2,6,0,0,0,2,6,0,1
65861,78596,0.619101,tcp,-,FIN,10,6,586,268,24.228680,...,2,1,7,0,0,0,2,6,0,0
65862,16431,0.513353,tcp,http,FIN,12,26,1620,27492,72.075162,...,1,1,1,0,0,1,19,1,0,1
65863,59007,0.350092,tcp,-,FIN,8,8,364,968,42.845881,...,1,1,2,0,0,0,2,2,0,1
65864,74621,1.053994,tcp,-,FIN,10,8,2516,354,16.129123,...,1,1,3,0,0,0,1,3,0,0

In [7]:
data_dict = pd.read_csv('data/data_dictionary.csv')

In [11]:
print(data_dict)

          column_name                                        description  \
0                  id        Unique identifier of the network connection
1                 dur                 Duration of the network connection
2               proto                              Network protocol used
3             service                               Network service used
4               state                                   Connection state
5               spkts                             Number of packets sent
6               dpkts                         Number of packets received
7              sbytes                               Number of bytes sent
8              dbytes                           Number of bytes received
9                rate                               Connection data rate
10               sttl           Source to destination time-to-live value
11               dttl           Destination to source time-to-live value
12              sload                             Source bits per second
13              dload                        Destination bits per second
14              sloss             Number of packets lost from the source
15              dloss        Number of packets lost from the destination
16             sinpkt   Average interval between packets from the source
17             dinpkt  Average interval between packets from the dest...
18               sjit                               Source packet jitter
19               djit                          Destination packet jitter
20               swin              Source TCP window advertisement value
21              stcpb                    Source TCP base sequence number
22              dtcpb               Destination TCP base sequence number
23               dwin         Destination TCP window advertisement value
24             tcprtt                                TCP round trip time
25             synack               Time between SYN and SYN-ACK packets
26             ackdat               Time between SYN-ACK and ACK packets
27              smean                   Mean packet size from the source
28              dmean              Mean packet size from the destination
29        trans_depth  Transaction depth of the HTTP request or response
30  response_body_len                   Length of the HTTP response body
31         ct_srv_src  Count of connections having the same service a...
32       ct_state_ttl  Count of connections having the same state and...
33         ct_dst_ltm  Count of connections to the same destination w...
34   ct_src_dport_ltm  Count of connections from the same source to t...
35   ct_dst_sport_ltm  Count of connections from the same destination...
36     ct_dst_src_ltm  Count of connections having the same destinati...
37       is_ftp_login  Whether the connection contains a valid FTP login
38         ct_ftp_cmd           Number of FTP commands in the connection
39   ct_flw_http_mthd           Number of HTTP methods in the connection
40         ct_src_ltm  Count of connections from the same source with...
41         ct_srv_dst  Count of connections having the same service a...
42    is_sm_ips_ports  Whether source and destination IPs and ports a...
43              label  Whether the network connection is an attack or...

      data_type
0       Integer
1       Numeric
2   Categorical
3   Categorical
4   Categorical
5       Numeric
6       Numeric
7       Numeric
8       Numeric
9       Numeric
10      Numeric
11      Numeric
12      Numeric
13      Numeric
14      Numeric
15      Numeric
16      Numeric
17      Numeric
18      Numeric
19      Numeric
20      Numeric
21      Numeric
22      Numeric
23      Numeric
24      Numeric
25      Numeric
26      Numeric
27      Numeric
28      Numeric
29      Numeric
30      Numeric
31      Numeric
32      Numeric
33      Numeric
34      Numeric
35      Numeric
36      Numeric
37       Binary
38      Numeric
39      Numeric
40      Numeric
41      Numeric
42       Binary
43       Binary

# Performing EDA on Dataset

In [17]:
print("First 5 rows of the dataset : ")
print(df.head())

First 5 rows of the dataset :
      id       dur proto service state  spkts  dpkts  sbytes  dbytes  \
0  46264  1.457374   tcp    http   FIN     10     16     814    9878
1   3575  0.654355   tcp       -   FIN     10      8     564     354
2  43204  0.000002   udp       -   INT      2      0    1064       0
3  59869  0.000011   nvp       -   INT      2      0     180       0
4   1203  0.000004   udp       -   INT      2      0     168       0

            rate  ...  ct_src_dport_ltm  ct_dst_sport_ltm  ct_dst_src_ltm  \
0      17.154142  ...                 1                 1               1
1      25.979782  ...                 1                 1               1
2  500000.001300  ...                 9                 1              34
3   90909.090200  ...                14                14              14
4  250000.000600  ...                 1                 1               1

   is_ftp_login  ct_ftp_cmd  ct_flw_http_mthd  ct_src_ltm  ct_srv_dst  \
0             0           0                 1           2           1
1             0           0                 0           1           1
2             0           0                 0          10          33
3             0           0                 0          15          14
4             0           0                 0           1           1

   is_sm_ips_ports  label
0                0      1
1                0      1
2                0      0
3                0      1
4                0      1

[5 rows x 44 columns]

In [18]:
print("Last 5 rows of the dataset : ")
print(df.tail())

Last 5 rows of the dataset :
          id       dur      proto service state  spkts  dpkts  sbytes  dbytes  \
65860    718  0.000005  ipv6-opts       -   INT      2      0     200       0
65861  78596  0.619101        tcp       -   FIN     10      6     586     268
65862  16431  0.513353        tcp    http   FIN     12     26    1620   27492
65863  59007  0.350092        tcp       -   FIN      8      8     364     968
65864  74621  1.053994        tcp       -   FIN     10      8    2516     354

                rate  ...  ct_src_dport_ltm  ct_dst_sport_ltm  ct_dst_src_ltm  \
65860  200000.005100  ...                 2                 2               6
65861      24.228680  ...                 2                 1               7
65862      72.075162  ...                 1                 1               1
65863      42.845881  ...                 1                 1               2
65864      16.129123  ...                 1                 1               3

       is_ftp_login  ct_ftp_cmd  ct_flw_http_mthd  ct_src_ltm  ct_srv_dst  \
65860             0           0                 0           2           6
65861             0           0                 0           2           6
65862             0           0                 1          19           1
65863             0           0                 0           2           2
65864             0           0                 0           1           3

       is_sm_ips_ports  label
65860                0      1
65861                0      0
65862                0      1
65863                0      1
65864                0      0

[5 rows x 44 columns]

In [19]:
print("Shape of the dataset : ", df.shape)

Shape of the dataset :  (65865, 44)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 65865 entries, 0 to 65864
Data columns (total 44 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 65865 non-null  int64
 1   dur                65865 non-null  float64
 2   proto              65865 non-null  str
 3   service            65865 non-null  str
 4   state              65865 non-null  str
 5   spkts              65865 non-null  int64
 6   dpkts              65865 non-null  int64
 7   sbytes             65865 non-null  int64
 8   dbytes             65865 non-null  int64
 9   rate               65865 non-null  float64
 10  sttl               65865 non-null  int64
 11  dttl               65865 non-null  int64
 12  sload              65865 non-null  float64
 13  dload              65865 non-null  float64
 14  sloss              65865 non-null  int64
 15  dloss              65865 non-null  int64
 16  sinpkt             65865 non-null  float64
 17  dinpkt             65865 non-null  float64
 18  sjit               65865 non-null  float64
 19  djit               65865 non-null  float64
 20  swin               65865 non-null  int64
 21  stcpb              65865 non-null  int64
 22  dtcpb              65865 non-null  int64
 23  dwin               65865 non-null  int64
 24  tcprtt             65865 non-null  float64
 25  synack             65865 non-null  float64
 26  ackdat             65865 non-null  float64
 27  smean              65865 non-null  int64
 28  dmean              65865 non-null  int64
 29  trans_depth        65865 non-null  int64
 30  response_body_len  65865 non-null  int64
 31  ct_srv_src         65865 non-null  int64
 32  ct_state_ttl       65865 non-null  int64
 33  ct_dst_ltm         65865 non-null  int64
 34  ct_src_dport_ltm   65865 non-null  int64
 35  ct_dst_sport_ltm   65865 non-null  int64
 36  ct_dst_src_ltm     65865 non-null  int64
 37  is_ftp_login       65865 non-null  int64
 38  ct_ftp_cmd         65865 non-null  int64
 39  ct_flw_http_mthd   65865 non-null  int64
 40  ct_src_ltm         65865 non-null  int64
 41  ct_srv_dst         65865 non-null  int64
 42  is_sm_ips_ports    65865 non-null  int64
 43  label              65865 non-null  int64
dtypes: float64(11), int64(30), str(3)
memory usage: 22.1 MB

In [21]:
df.describe()

,id,dur,spkts,dpkts,sbytes,dbytes,rate,sttl,dttl,sload,...,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,label
count,65865.000000,65865.000000,65865.000000,65865.000000,6.586500e+04,6.586500e+04,6.586500e+04,65865.000000,65865.000000,6.586500e+04,...,65865.000000,65865.000000,65865.000000,65865.000000,65865.000000,65865.000000,65865.000000,65865.000000,65865.000000,65865.000000
mean,41207.961315,0.987311,18.519821,17.462385,7.987310e+03,1.313970e+04,8.249203e+04,181.068337,95.720793,6.411705e+07,...,4.937372,3.669612,7.457800,0.008199,0.008275,0.129735,6.476308,9.163653,0.011038,0.550596
std,23776.952744,4.621790,139.862731,122.649767,1.801333e+05,1.609088e+05,1.486454e+05,101.465131,116.680469,1.759029e+08,...,8.411122,5.928869,11.417763,0.090511,0.091588,0.644568,8.567688,11.120887,0.104480,0.497437
min,1.000000,0.000000,1.000000,0.000000,2.400000e+01,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,20632.000000,0.000008,2.000000,0.000000,1.140000e+02,0.000000e+00,2.860079e+01,62.000000,0.000000,1.118218e+04,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000
50%,41227.000000,0.014000,6.000000,2.000000,5.340000e+02,1.780000e+02,2.664298e+03,254.000000,29.000000,5.796287e+05,...,1.000000,1.000000,3.000000,0.000000,0.000000,0.000000,3.000000,5.000000,0.000000,1.000000
75%,61755.000000,0.717918,12.000000,10.000000,1.278000e+03,9.320000e+02,1.111111e+05,254.000000,252.000000,6.514286e+07,...,4.000000,3.000000,6.000000,0.000000,0.000000,0.000000,7.000000,11.000000,0.000000,1.000000
max,82332.000000,59.999989,10646.000000,11018.000000,1.435577e+07,1.465753e+07,1.000000e+06,255.000000,253.000000,5.268000e+09,...,59.000000,38.000000,63.000000,2.000000,2.000000,16.000000,60.000000,62.000000,1.000000,1.000000

In [23]:
print("Missing values ", df.isnull().sum().sum())

Missing values  0